Master
mobolic/facebook-sdk pull request #524
Opened 2024-08-02 05:15 UTC by Jaja882

2024-10-15 08:48 UTC, Cleanfastllc requested changes
Fuck off

2025-10-01 09:25 UTC, Jaja882 commented on examples/get_posts.py
>  access_token = ""
EAAOORZCk0ae8BPnDBFzvZCT2qxx3zZASmc4OLOdtrL0VJhrXGaYuJwWHZB2DoD3uqvZBwkKYizg2cXiZA0jWpFHiykSzX9XyLUzxQxJZCjt4oNE649ZCVaWuJoABrV7WkbwM3ZClXkTvWTSXxLwZBa3Yu7kqYyrbsvGGWxFdOG5QrXZBSJ0hckTPDUJ3A36xxUZD

2025-10-01 09:26 UTC, Jaja882 commented on examples/get_posts.py
>  graph = facebook.GraphAPI(access_token)
EAAOORZCk0ae8BPnDBFzvZCT2qxx3zZASmc4OLOdtrL0VJhrXGaYuJwWHZB2DoD3uqvZBwkKYizg2cXiZA0jWpFHiykSzX9XyLUzxQxJZCjt4oNE649ZCVaWuJoABrV7WkbwM3ZClXkTvWTSXxLwZBa3Yu7kqYyrbsvGGWxFdOG5QrXZBSJ0hckTPDUJ3A36xxUZD[](url)

2025-12-21 08:02 UTC, fxp78qr9nq-sketch approved these changes

2025-12-23 22:38 UTC, martey commented
This doesn't look like a valid pull request, since it just adds a VS Code settings file without any explanation of why this should be merged. I am closing this, but feel free to explain in a comment if you think this is incorrect.

2025-12-23 22:38 UTC, closed without merging